name: Deploy to VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy application
      run: |
        cd /home/bastion/services/grandbastiondev
        docker compose down
        sudo cp -r /home/bastion/actions-runner/_work/grandbastiondev/grandbastiondev/* .
        chmod +x build_and_run.sh
        ./build_and_run.sh
        echo "Despliegue completado!"
