name: Deploy to VPS

on:
  push:
    branches:
      - main # Desencadena el workflow en cada push a la rama 'main'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy application
      run: |
        cd /home/${{ secrets.SSH_USER }}/services/grandbastiondev
        sudo cp -r /home/${{ secrets.SSH_USER }}/actions-runner/_work/grandbastiondev/grandbastiondev/* .
        chmod +x build_and_run.sh
        ./build_and_run.sh
        echo "Despliegue completado!"
